language: objective-c
xcode_sdk: iphonesimulator
xcode_scheme: MMDrawerControllerKitchenSink
xcode_workspace: KitchenSink/MMDrawerControllerKitchenSink.xcworkspace
before_install:
  - brew update
  - brew reinstall xctool
  - gem update cocoapods
  - gem install slather
after_success:
  - slather
